# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWLb-WnQ8iISeh7DW6YLrHSdHVPGV_J8
"""

!pip install -q peft transformers datasets accelerate trl bitsandbytes





from google.colab import files
uploaded = files.upload()  # Upload your dataset.jsonl

from datasets import load_dataset

dataset = load_dataset("json", data_files="dataset.jsonl", split="train")
print(f"✅ Loaded {len(dataset)} examples")

from transformers import AutoTokenizer

base_model = "gpt2-large"
tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token  # GPT2 doesn't have a pad token

def tokenize_function(example):
    full_prompt = f"Instruction: {example['instruction']}\n{example['input']}\nPost: {example['output']}"
    tokenized = tokenizer(full_prompt, truncation=True, padding="max_length", max_length=150)
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_dataset = dataset.map(tokenize_function, batched=False)
tokenized_dataset.set_format("torch")

from transformers import AutoModelForCausalLM
from peft import get_peft_model, LoraConfig, TaskType

model = AutoModelForCausalLM.from_pretrained(base_model)
model.resize_token_embeddings(len(tokenizer))  # in case tokenizer resized

peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./gpt2-lora-checkpoints",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=2,
    logging_steps=10,
    num_train_epochs=3,
    save_strategy="epoch",
    learning_rate=2e-4,
    fp16=True,
    report_to="none",
)

from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_dataset,
    args=training_args,
    peft_config=peft_config,
)

trainer.train()

from trl import SFTTrainer

trainer = SFTTrainer(
    model=model,
    train_dataset=tokenized_dataset,
    args=training_args,
    peft_config=peft_config,
)

trainer.train()

model.save_pretrained("./gpt2-lora-adapter")
tokenizer.save_pretrained("./gpt2-lora-adapter")

from transformers import pipeline
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import word_tokenize
import nltk

# Ensure punkt is downloaded
nltk.download("punkt", download_dir="/usr/share/nltk_data")
import nltk.data
nltk.data.path.append("/usr/share/nltk_data")

# Set up generator
generator = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)

# Prompt parts
instruction = "Write a quirky social media post."
brand = "Starbucks"
news = "AI-designed traffic system reduces city congestion by 30%."
input_block = f"Brand: {brand}\nNews: {news}"
prompt = f"Instruction: {instruction}\n{input_block}\nPost:"

# Generate
output = generator(prompt, max_new_tokens=100, do_sample=True, temperature=0.9)[0]['generated_text']
print("📝 Prompt:\n", prompt)
print("\n🎯 Model Output:\n", output)

# Reference
reference = ["Traffic’s flowing smoother than cold brew on a Monday. Thanks, AI! 🚦☕️"]
candidate = output.split("Post:")[-1].strip()

# BLEU Score
score = sentence_bleu(
    [word_tokenize(reference[0])],
    word_tokenize(candidate),
    smoothing_function=SmoothingFunction().method4
)
print(f"\n🔍 BLEU Score: {score:.2f}")