sonar.projectKey=News2Buzz
sonar.projectName=News2Buzz
sonar.projectVersion=1.0

sonar.sources=backend,Frontend,Generative_Model,Web Scraper

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login= sqp_2e91c57d918b66fa61de722fdb75bff052b9bb78
