version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: backend
    ports:
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    depends_on:
      - elasticsearch
      - mongodb

  news_api:
    build:
      context: .
      dockerfile: Dockerfile.news
    container_name: news_api
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
      - mongodb

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    restart: always
