# -*- coding: utf-8 -*-
"""Base_Model_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8PrYXsG15FAOEM6I_2Irj36ilJdQsBD
"""

from google.colab import drive
drive.mount('/content/drive')

pip install diffusers transformers accelerate safetensors

from diffusers import StableDiffusionPipeline

import torch
from diffusers import StableDiffusionXLPipeline

base_model = "stabilityai/stable-diffusion-xl-base-1.0"
pipe = StableDiffusionXLPipeline.from_pretrained(base_model, torch_dtype=torch.float16)
pipe.to("cuda")

pipe.load_lora_weights("artificialguybr/StickersRedmond", weight_name="StickersRedmond.safetensors")

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "A cute real cat holding a pet, colorful sticker style"
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "A colorful sticker of a breaking news headline with a newspaper, globe, and red alert symbol, flat design."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "Sticker of a TV news anchor in a studio with a microphone, bright colors, and a modern style."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "Sticker of a political rally with flags waving and a podium, flat vector art style, bright colors."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "Sticker of a global political summit with leaders shaking hands, cartoon style."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

Colorful sticker of a bank building with gold coins and a vault, flat design.

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "Colorful sticker of a bank building with gold coins and a vault, flat design."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "A detailed sticker of a globe surrounded by breaking news symbols, satellites transmitting signals, news anchors reporting in modern offices with large monitors, and a mix of political, economic, and sports news highlights visible on the screens. The image reflects urgency and accuracy with vibrant colors and detailed cartoon textures."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

import matplotlib.pyplot as plt

# Generate the sticker
prompt = "A high-detail sticker showing a modern stock exchange floor with traders in suits shouting orders, large monitors displaying green and red stock charts, and financial headlines like 'Market Crash' and 'Tech Stocks Soar' flashing across the screen. The scene reflects urgency with modern lighting and a clean cartoon design."
result = pipe(prompt, height=512, width=512, num_inference_steps=20, guidance_scale=5).images[0]

# Display using matplotlib
plt.figure(figsize=(3, 3))  # Smaller figure size
plt.imshow(result)
plt.axis('off')  # Remove axes
plt.tight_layout(pad=0)  # Remove extra padding
plt.show()

