# -*- coding: utf-8 -*-
"""fine-tuning-emoji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TN1yN-NzsgXM7Im4ut_WRLKnURt9r7pr
"""

!pip install transformers datasets torch torchvision pandas scikit-learn matplotlib tqdm

import os
import torch
import pandas as pd
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import load_dataset, DatasetDict
from sklearn.model_selection import train_test_split
from PIL import Image
from tqdm import tqdm

from google.colab import drive
drive.mount('/content/drive')

# Load CSV dataset
csv_path = "/content/drive/MyDrive/full_emoji.csv"
df = pd.read_csv(csv_path)

# Check the first few rows
print(df.head())

# Ensure required columns exist (assuming 'text' and 'emoji' are the main columns)
if "name" not in df.columns or "emoji" not in df.columns:
    raise ValueError("The dataset must contain 'text' and 'emoji' columns.")

# Train-test split
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# Save split datasets
train_df.to_csv("train.csv", index=False)
test_df.to_csv("test.csv", index=False)

print("Dataset split completed.")

# Load a pre-trained tokenizer
model_name = "KoalaAI/Emoji-Suggester"  # Ensure this is the correct model
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Function to tokenize input text
def tokenize_function(examples):
    return tokenizer(examples["name"], padding="max_length", truncation=True, max_length=512)

# Load the dataset using Hugging Face's `datasets` library
dataset = load_dataset('csv', data_files={'train': 'train.csv', 'test': 'test.csv'})

# Tokenize dataset
tokenized_datasets = dataset.map(tokenize_function, batched=True)

# Create label mapping (emoji → numeric ID)
unique_labels = df["emoji"].unique()
label2id = {label: idx for idx, label in enumerate(unique_labels)}
id2label = {idx: label for label, idx in label2id.items()}

# Map emoji labels to numeric IDs
def encode_labels(dataset):
    dataset = dataset.map(lambda x: {"label": label2id[x["emoji"]]})
    return dataset

tokenized_datasets["train"] = encode_labels(tokenized_datasets["train"])
tokenized_datasets["test"] = encode_labels(tokenized_datasets["test"])

num_labels = len(label2id)
print(f"Dataset encoding completed. Number of labels: {num_labels}")

# Define a custom PyTorch dataset to load images
class EmojiDataset(Dataset):
    def __init__(self, dataframe, image_folder, tokenizer):
        self.data = dataframe
        self.image_folder = image_folder
        self.tokenizer = tokenizer
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
        ])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        text = self.data.iloc[idx]["text"]
        label = label2id[self.data.iloc[idx]["emoji"]]
        image_path = os.path.join(self.image_folder, self.data.iloc[idx]["image"])

        # Load and preprocess image
        image = Image.open(image_path).convert("RGB")
        image = self.transform(image)

        # Tokenize text
        tokens = self.tokenizer(text, padding="max_length", truncation=True, return_tensors="pt")

        return {
            "input_ids": tokens["input_ids"].squeeze(),
            "attention_mask": tokens["attention_mask"].squeeze(),
            "image": image,
            "label": torch.tensor(label, dtype=torch.long),
        }

# Define dataset path
image_folder = "/content/drive/MyDrive/image"
train_dataset = EmojiDataset(train_df, image_folder, tokenizer)
test_dataset = EmojiDataset(test_df, image_folder, tokenizer)

# Create DataLoader
train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=8, shuffle=False)

print("Image dataset loaded successfully.")

# Load the pre-trained model
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./fine_tuned_emoji_model",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=10,
    save_total_limit=2,
    report_to="none"
)

# Define trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
)

print("Model loaded and trainer initialized.")

trainer.train()
print("Model fine-tuning complete!")

# Save the fine-tuned model
model.save_pretrained("./fine_tuned_emoji_model")
tokenizer.save_pretrained("./fine_tuned_emoji_model")

print("Fine-tuned model saved successfully.")

from transformers import pipeline

# Load fine-tuned model
fine_tuned_model = AutoModelForSequenceClassification.from_pretrained("./fine_tuned_emoji_model")
fine_tuned_tokenizer = AutoTokenizer.from_pretrained("./fine_tuned_emoji_model")

# Define prediction pipeline
emoji_pipeline = pipeline("text-classification", model=fine_tuned_model, tokenizer=fine_tuned_tokenizer)

# Test on a sample news headline
sample_text = "Stock markets are crashing worldwide due to economic slowdown."
predicted_emoji_id = emoji_pipeline(sample_text)[0]['label']
predicted_emoji = id2label[int(predicted_emoji_id)]

print(f"Predicted emoji: {predicted_emoji}")

