# -*- coding: utf-8 -*-
"""Loss_is_nan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwRh-nUwogcZNT9m8fpYWBYaOYRQ2pqw
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install diffusers==0.25.0 transformers==4.37.2 accelerate==0.27.2 \
huggingface_hub==0.20.3 peft==0.7.1 bitsandbytes safetensors --upgrade

#!pip install diffusers accelerate transformers datasets safetensors torch torchvision peft

#!pip install bitsandbytes
#!pip install --upgrade transformers diffusers accelerate

import numpy as np
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer
import json

from peft import LoraConfig, get_peft_model
from transformers import CLIPTextModel, CLIPTokenizer, BitsAndBytesConfig

import os
import torch

from torchvision import transforms

from diffusers import StableDiffusionPipeline, AutoencoderKL

"""**# Set paths**"""

# STEP 3: Load and Verify Dataset
image_folder = "/content/drive/MyDrive/AIP_Project/week 11/Final DATASETS/resized_imgs1"
json_path = "/content/drive/MyDrive/AIP_Project/week 11/Final DATASETS/Clean_json/cleaned_dataset_filtered.json"

with open(json_path, "r") as f:
    dataset = json.load(f)

print("Total Images:", len(os.listdir(image_folder)))
print("Total JSON Entries:", len(dataset))

"""**# Load pipeline and use tokenizer from it**

# STEP 1 — Model & Pipeline Setup
"""

# Load pipeline
from diffusers import StableDiffusionPipeline
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

from diffusers.models.attention_processor import LoRAAttnProcessor

# Step 1: Create LoRA attention processors
lora_attn_procs = {}
for name in pipe.unet.attn_processors.keys():
    lora_attn_procs[name] = LoRAAttnProcessor(
        hidden_size=pipe.unet.config.block_out_channels[0],  # 320 usually
        cross_attention_dim=pipe.unet.config.cross_attention_dim,
        rank=4,
        lora_alpha=16,
        dropout=0.1
    )

# Step 2: Apply them to the UNet
pipe.unet.set_attn_processor(lora_attn_procs)

# Step 3: Move model to float16 and GPU
pipe.unet.to("cuda", dtype=torch.float16)
pipe.vae.to("cuda", dtype=torch.float16)

print("✅ LoRA processors applied and UNet/VAE ready.")

"""**load based model**"""

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

from diffusers.models.attention_processor import LoRAAttnProcessor

lora_attn_procs = {}

for name in pipe.unet.attn_processors.keys():
    is_cross_attention = name.endswith("attn2.processor")

    hidden_size = None
    if "mid_block" in name:
        hidden_size = pipe.unet.config.block_out_channels[-1]
    elif "up_blocks" in name:
        block_id = int(name.split(".")[1])
        hidden_size = list(reversed(pipe.unet.config.block_out_channels))[block_id]
    elif "down_blocks" in name:
        block_id = int(name.split(".")[1])
        hidden_size = pipe.unet.config.block_out_channels[block_id]

    cross_attention_dim = pipe.unet.config.cross_attention_dim if is_cross_attention else None

    # ✅ Now pass required args
    lora_attn_procs[name] = LoRAAttnProcessor(
        hidden_size=hidden_size,
        cross_attention_dim=cross_attention_dim,
        rank=4,
        lora_alpha=16,
        dropout=0.1
    )

pipe.unet.set_attn_processor(lora_attn_procs)
pipe.unet.to("cuda", dtype=torch.float16)
pipe.vae.to("cuda", dtype=torch.float16)

print("✅ LoRA processors applied with required arguments.")





"""# Attach LoRA to to_q, to_k, to_v, to_out.0"""





# STEP 5: Load Tokenizer, Text Encoder, and VAE

from transformers import CLIPTokenizer, CLIPTextModel
from diffusers import AutoencoderKL

try:
    tokenizer = CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")
    text_encoder = CLIPTextModel.from_pretrained("openai/clip-vit-large-patch14").to("cuda")
    vae = AutoencoderKL.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="vae").to("cuda")
    print("✅ Tokenizer, Text Encoder, and VAE loaded successfully.")
except Exception as e:
    print("❌ Error loading components:")
    raise e

"""**clen json entry**"""

# Reload original JSON to avoid accidental overwrites
import json

with open(json_path, "r") as f:
    raw_data = json.load(f)

# ✅ Filter entries with valid "image_sticker_name"
cleaned_data = [entry for entry in raw_data if isinstance(entry, dict) and "image_sticker_name" in entry]

print(f"✅ Cleaned dataset: {len(cleaned_data)} valid entries out of {len(raw_data)} total.")

"""**Patch the StickerDataset to catch and skip broken entries**"""

from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import torch
import os

class StickerDataset(Dataset):
    def __init__(self, data, image_dir, tokenizer, text_encoder, vae):
        self.data = data
        self.image_dir = image_dir
        self.tokenizer = tokenizer
        self.text_encoder = text_encoder
        self.vae = vae
        self.device = torch.device("cuda")

        self.transform = transforms.Compose([
            transforms.ToTensor()  # Normalizes image to [0, 1]
        ])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        try:
            entry = self.data[idx]

            # Validate JSON format
            if "image_sticker_name" not in entry:
                raise KeyError("'image_sticker_name' key not found.")

            image_name = entry["image_sticker_name"]
            image_path = os.path.join(self.image_dir, image_name)

            # Load image
            image = Image.open(image_path).convert("RGB")
            image = self.transform(image)

            # Parse prompt text
            prompt = image_name.rsplit("_", 1)[0].strip()

            # Tokenize + move to correct device
            tokenized = self.tokenizer(
                prompt,
                padding="max_length",
                truncation=True,
                max_length=77,
                return_tensors="pt"
            )
            tokenized = {k: v.to(self.device) for k, v in tokenized.items()}

            # Get text encoder hidden states
            with torch.no_grad():
                encoder_hidden_states = self.text_encoder(**tokenized).last_hidden_state.squeeze(0)

            return {
                "sample": image,
                "timestep": torch.randint(0, 1000, (1,)).long().squeeze(0),
                "encoder_hidden_states": encoder_hidden_states
            }

        except Exception as e:
            print(f"❌ Error in dataset item {idx}: {e}")
            raise e

dataset = StickerDataset(cleaned_data, image_folder, pipe.tokenizer, pipe.text_encoder, pipe.vae)
dataloader = DataLoader(dataset, batch_size=8, shuffle=True, pin_memory=False)

import torch.nn.functional as F
from tqdm import tqdm

# Collect only trainable LoRA parameters
lora_params = [p for n, p in pipe.unet.named_parameters() if p.requires_grad]
optimizer = torch.optim.AdamW(lora_params, lr=2e-6)

num_epochs = 4  # Start with 1 epoch for testing
print("🟢 Starting LoRA training (clean + float16)...")

try:
    for epoch in range(num_epochs):
        total_loss = 0
        progress = tqdm(dataloader, desc=f"Epoch {epoch+1}/{num_epochs}")

        for i, batch in enumerate(progress):
            optimizer.zero_grad()

            try:
                # Move all inputs to GPU
                images = batch["sample"].to("cuda", dtype=torch.float16)
                timesteps = batch["timestep"].to("cuda")
                encoder_hidden_states = batch["encoder_hidden_states"].to("cuda", dtype=torch.float16)

                # Encode images to latents
                with torch.no_grad():
                    latents = pipe.vae.encode(images).latent_dist.sample() * 0.18215

                # Add noise
                noise = torch.randn_like(latents)
                noisy_latents = latents + noise * 0.1

                # Print dtypes once
                if i == 0:
                    print("🔍 Precision Check:")
                    print("  images:", images.dtype)
                    print("  latents:", latents.dtype)
                    print("  noise:", noise.dtype)
                    print("  encoder_hidden_states:", encoder_hidden_states.dtype)

                # UNet forward pass
                output = pipe.unet(noisy_latents, timesteps, encoder_hidden_states)
                predicted_noise = output.sample if hasattr(output, "sample") else output[0]

                # Compute loss
                loss = F.mse_loss(predicted_noise, noise)
                loss.backward()
                optimizer.step()

                total_loss += loss.item()
                progress.set_postfix({"loss": loss.item()})

            except Exception as batch_err:
                print(f"❌ Error in batch {i}:\n{batch_err}")
                raise batch_err

        avg_loss = total_loss / len(dataloader)
        print(f"✅ Epoch {epoch+1} completed. Avg Loss: {avg_loss:.6f}")

except Exception as e:
    print("❌ Training loop crashed:")
    print(str(e))







pipe.unet.to("cuda", dtype=torch.float16)
pipe.vae.to("cuda", dtype=torch.float16)

import torch.nn.functional as F
from tqdm import tqdm

# ✅ Collect only LoRA parameters
lora_params = [p for n, p in pipe.unet.named_parameters() if p.requires_grad]
optimizer = torch.optim.AdamW(lora_params, lr=2e-6)

num_epochs = 1  # Run 1 epoch first to verify everything works
print("🟢 Starting LoRA training (clean + float16)...")

try:
    for epoch in range(num_epochs):
        total_loss = 0
        progress = tqdm(dataloader, desc=f"Epoch {epoch+1}/{num_epochs}")

        for i, batch in enumerate(progress):
            optimizer.zero_grad()

            try:
                # Move batch to GPU
                images = batch["sample"].to("cuda", dtype=torch.float16)
                timesteps = batch["timestep"].to("cuda")
                encoder_hidden_states = batch["encoder_hidden_states"].to("cuda")

                # VAE encoding to latent space (float16-safe)
                with torch.no_grad():
                    latents = pipe.vae.encode(images).latent_dist.sample() * 0.18215

                # Add noise
                noise = torch.randn_like(latents)
                noisy_latents = latents + noise * 0.1

                # Debug precision once
                if i == 0:
                    print("🔍 Precision Check:")
                    print("  images:", images.dtype)
                    print("  latents:", latents.dtype)
                    print("  noise:", noise.dtype)
                    print("  encoder_hidden_states:", encoder_hidden_states.dtype)

                # UNet forward pass
                predicted_noise = pipe.unet(noisy_latents, timesteps, encoder_hidden_states)[0]

                # Loss + Backward
                loss = F.mse_loss(predicted_noise, noise)
                loss.backward()
                optimizer.step()

                total_loss += loss.item()
                progress.set_postfix({"loss": loss.item()})

            except Exception as batch_err:
                print(f"❌ Error in batch {i}:\n{batch_err}")
                raise batch_err

        avg_loss = total_loss / len(dataloader)
        print(f"✅ Epoch {epoch+1} completed. Avg Loss: {avg_loss:.6f}")

except Exception as e:
    print("❌ Training loop crashed:")
    print(str(e))

