input {
  file {
    path => "/app/news_articles.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"  # Ensures re-processing the file on restart
    codec => "json"
  }
}

filter {
  if [message] {
    json {
      source => "message"
    }
  }

  mutate {
    rename => { "headline" => "headline" }
    rename => { "link" => "link" }
    rename => { "short_description" => "short_description" }
    rename => { "timestamp" => "timestamp" }
    remove_field => ["message", "_id", "host", "path", "tags"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "news_articles"
  }
  stdout { codec => rubydebug }
}
