input {
  mongodb {
    uri => 'mongodb://mongodb:27017/news_database'
    placeholder_db_dir => '/usr/share/logstash/mongodb/'
    placeholder_db_name => 'logstash_sqlite.db'
    collection => 'news_articles'
    batch_size => 500
  }
}

filter {
  date {
    match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["_id","log_entry","logdate","mongo_id","timestamp","host","headline_clean","headline_entities","short_description_clean","short_description_entities","sentiment_scores"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "news_articles"
  }
  stdout { codec => rubydebug }
}
