# filepath: C:\Users\JITENDER KAUSHIK\Desktop\ELK\Data_Pipeline\Final_data_pipeline\producer\Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Command to run the producer script
CMD ["python", "kafka_producer.py"]